/* DO NOT EDIT THIS FILE - it is machine generated */
#include "libs/jni/jni.h"
/* Header for class myDefinedClass */

#ifndef _Included_myDefinedClass
#define _Included_myDefinedClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeVoid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_myDefinedClass_nativeBridgeVoid
  (JNIEnv *, jclass);

/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeBool
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_myDefinedClass_nativeBridgeBool
  (JNIEnv *, jclass);

/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeByte
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_myDefinedClass_nativeBridgeByte
  (JNIEnv *, jclass);

/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_myDefinedClass_nativeBridgeChar
  (JNIEnv *, jclass);

/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeShort
 * Signature: ()S
 */
JNIEXPORT jshort JNICALL Java_myDefinedClass_nativeBridgeShort
  (JNIEnv *, jclass);

/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeInt
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_myDefinedClass_nativeBridgeInt
  (JNIEnv *, jclass);

/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeLong
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_myDefinedClass_nativeBridgeLong
  (JNIEnv *, jclass);

/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeFloat
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_myDefinedClass_nativeBridgeFloat
  (JNIEnv *, jclass);

/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeDouble
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_myDefinedClass_nativeBridgeDouble
  (JNIEnv *, jclass);

/*
 * Class:     myDefinedClass
 * Method:    nativeBridgeObject
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_myDefinedClass_nativeBridgeObject
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
